"""procesio tool entrypoint - action dispatch over the PROCESIO Web API.

Dual auth (API key OR username/password -> Bearer) with a multi-credential
profile store; a generic `request` action covering every documented endpoint;
curated read/run actions for the common surface.
"""
from __future__ import annotations

import sys
from pathlib import Path

TOOL_ROOT = Path(__file__).resolve().parent
FRAMEWORK_ROOT = TOOL_ROOT.parents[1]
# .venv layout is per-OS: Scripts/python.exe on Windows, bin/python everywhere else.
_VENV_PY = (FRAMEWORK_ROOT / ".venv" / "Scripts" / "python.exe" if sys.platform == "win32"
            else FRAMEWORK_ROOT / ".venv" / "bin" / "python")
if _VENV_PY.exists() and Path(sys.executable).resolve() != _VENV_PY.resolve():
    import subprocess
    sys.exit(subprocess.run([str(_VENV_PY), __file__, *sys.argv[1:]]).returncode)

import argparse  # noqa: E402

if str(FRAMEWORK_ROOT) not in sys.path:
    sys.path.insert(0, str(FRAMEWORK_ROOT))

from tools._lib.io import emit, fail  # noqa: E402
from tools.procesio import errors  # noqa: E402
from tools.procesio.actiondef import ActionDef  # noqa: E402
from tools.procesio.client import ProcesioClient  # noqa: E402


class _Parser(argparse.ArgumentParser):
    def error(self, message: str):
        raise errors.UsageError(message)


# Known footguns on raw/autogenerated endpoints: the call SUCCEEDS but leaves the
# workspace in a state the caller rarely intends. Attached to the emitted JSON as
# `warning` so it is visible without changing the action's contract. One line per
# action; keep the text actionable.
ADVISORIES = {
    "post-projects-by-id-instances-publish": (
        "publish CREATES an instance in status 1 ('starting') with 0 action runs and "
        "does NOT run it — publish and launch are a pair (run-process does both). A "
        "WEBHOOK-triggered process needs no publish at all: the webhook launch "
        "publishes+launches itself. Calling publish 'to activate' just accumulates "
        "instances stuck at 'starting' (they cannot be stopped via the API — only in "
        "the UI). Launch it with post-projects-instances-by-id-launch, or use "
        "run-process, or simply don't publish."
    ),
}


def _advise(action: str, result):
    """Attach a known-footgun advisory to a successful result (non-destructive)."""
    note = ADVISORIES.get(action)
    if note and isinstance(result, dict):
        result.setdefault("warning", note)
    return result


def collect_actions() -> dict[str, ActionDef]:
    from tools.procesio import autogen
    from tools.procesio.handlers import (
        auth_actions, catalog, customaction_ops, datastore_ops, datatype_ops,
        dto_actions, environment_admin, files,
        flowgraph, form_code, form_element, form_events, form_update, formprocess, generic, layout,
        process_layout, process_naming, processes, profile_admin,
        flowlint, fevalidate, nodeparams, resource_ops, schedules, sqlactions, transport,
    )
    # Curated / management actions: ergonomic, hand-written, well-tested.
    curated: dict[str, ActionDef] = {}
    curated.update(profile_admin.ACTIONS)
    # Environment registry: list/add/set/remove/show PROCESIO environments (URLs).
    curated.update(environment_admin.ACTIONS)
    curated.update(auth_actions.ACTIONS)
    curated.update(generic.ACTIONS)
    curated.update(processes.ACTIONS)
    # Submit a form the way a browser does (proves the form's own maps carry values).
    curated.update(formprocess.ACTIONS)
    curated.update(catalog.ACTIONS)
    curated.update(transport.ACTIONS)
    curated.update(schedules.ACTIONS)
    # Data Store: user-defined dynamic tables — metadata + row CRUD + CSV jobs.
    curated.update(datastore_ops.ACTIONS)
    # DTO sub-tools: <component>-create / <component>-edit (deterministic builders).
    curated.update(dto_actions.ACTIONS)
    # Full data-model lifecycle: attribute add/edit/delete, get/delete, changeToPublic, clone.
    curated.update(datatype_ops.ACTIONS)
    # File ops: download a flow-instance file (Generate-Document output etc.).
    curated.update(files.ACTIONS)
    # Custom-action (connector) lifecycle: upload .nupkg / delete / list.
    curated.update(customaction_ops.ACTIONS)
    # Offline structural reader: parse a flow/export into a node/edge graph model.
    curated.update(flowgraph.ACTIONS)
    # Offline deterministic canvas auto-layout (re-lay-out a flow; resource map).
    curated.update(layout.ACTIONS)
    # Live process ops that pair with layout: duplicate a process; re-lay-out in place.
    curated.update(process_layout.ACTIONS)
    # Bulk-rename a live process's canvas actions (default "Node"/"Call API" labels).
    curated.update(process_naming.ACTIONS)
    # CRUD-parity + verification oracles: get/delete/list, validate, credential/action test, import.
    curated.update(resource_ops.ACTIONS)
    # In-place read/write of a form's global CSS + JS (Data.code), without the
    # desired-state rebuild form-edit performs.
    curated.update(form_code.ACTIONS)
    # Same surgical shape, for one element's event handlers (RUN_PROCESS wiring).
    curated.update(form_events.ACTIONS)
    # Same surgical shape again, for one element's PLAIN configs — label/required/
    # regex/visible. Content and per-field rules belong in the DTO, not in the
    # form-level JS layer where the designer cannot see them.
    curated.update(form_element.ACTIONS)
    # Arbitrary safe save: GET a live form, deep-merge a Data patch (and/or override
    # name/status/state), PUT the accepted DTO — the general form-save form-edit isn't.
    curated.update(form_update.ACTIONS)
    # SQL Server action hardening: scan + convert inline <%N%> SQL to parameterized (@param) binding.
    curated.update(sqlactions.ACTIONS)
    # Surgical single-parameter edits on a live designer-built flow (endpoint/timeout/SQL/script):
    # read the parameter surface, patch one literal, regenerate the designer layer, validate, PUT.
    curated.update(nodeparams.ACTIONS)
    curated.update(flowlint.ACTIONS)
    # Front-end (designer-layer) validation: process-fe-validate + the pre-save gate that
    # auto-runs (FE then BE) before every process-create / process-edit.
    curated.update(fevalidate.ACTIONS)
    # Generated actions: full 1:1 coverage of every Web-API endpoint. Curated
    # names win on the (non-colliding) name space.
    actions = autogen.build_actions(reserved=set(curated))
    actions.update(curated)
    return actions


ACTIONS = collect_actions()


def dispatch(action: str, argv: list[str], *, client_builder=None) -> dict:
    if action not in ACTIONS:
        raise errors.UsageError(
            f"unknown action: {action}. Known: {', '.join(sorted(ACTIONS))}"
        )
    defn = ACTIONS[action]
    parser = _Parser(prog=f"procesio {action}", description=defn.description)
    defn.add_args(parser)
    parsed = parser.parse_args(argv)
    if defn.needs_client:
        profile = getattr(parsed, "profile", None)
        environment = getattr(parsed, "environment", None)
        builder = client_builder or (
            lambda prof: ProcesioClient(prof, environment=environment))
        client = builder(profile)
        wsid = getattr(parsed, "workspace_id", None)
        if wsid:
            client.workspace_id = wsid   # per-call active-workspace override
        return defn.func(client, parsed)
    return defn.func(parsed)


def main(argv=None) -> None:
    argv = list(sys.argv[1:] if argv is None else argv)
    if not argv or argv[0] in ("-h", "--help"):
        print("Actions:", file=sys.stderr)
        for name in sorted(ACTIONS):
            print(f"  {name:<22} {ACTIONS[name].description}", file=sys.stderr)
        sys.exit(0)
    action, rest = argv[0], argv[1:]
    try:
        result = dispatch(action, rest)
    except Exception as exc:  # noqa: BLE001
        code, message, details, exit_code = errors.classify(exc)
        fail(code, message, details, exit_code)
    emit(_advise(action, result))


if __name__ == "__main__":
    main()
