"""First-run detection + bootstrap of the user-data folder.

The wipe-safety contract: deleting context-state-knowledge/ must never break the
framework. Every component degrades to guidance ("no data - here is how to start"),
and this module is the guidance engine:

- **Templates** live in the FRAMEWORK, beside the component that owns them, as
  ``<name>.template.json`` (e.g. ``agents/email-classifier/accounts.template.json``).
  They contain placeholders only - never real user data - and map to
  ``context-state-knowledge/config/<component>/<name>.json``.
- **freshness()** decides "fresh start": zero records in the store AND zero files
  under config/. A brand-new (or wiped) install trips it; the orchestrator and
  curator surface it so the driver prompts the user instead of acting blind.
- **bootstrap()** seeds the folder: ensures the store schema (via the context-store
  tool - never opening the DB directly), regenerates the folder README, optionally
  copies templates (never overwriting), and returns the onboarding checklist.
"""
from __future__ import annotations

import shutil
from pathlib import Path

from tools._lib import userdata

FRAMEWORK_ROOT = Path(__file__).resolve().parents[2]

_TEMPLATE_SUFFIX = ".template.json"
# Only the top level of each component dir - deep matches would pick up fixtures.
_TEMPLATE_GLOBS = ("tools/*/*.template.json", "agents/*/*.template.json")


def find_templates() -> list[dict]:
    """Discover framework config templates and their user-data targets."""
    out: list[dict] = []
    base = userdata.base()
    for pattern in _TEMPLATE_GLOBS:
        for tpl in sorted(FRAMEWORK_ROOT.glob(pattern)):
            component = tpl.parent.name
            target_name = tpl.name[: -len(_TEMPLATE_SUFFIX)] + ".json"
            target = base / "config" / component / target_name
            out.append({
                "component": component,
                "template": str(tpl.relative_to(FRAMEWORK_ROOT)),
                "target": str(target),
                "target_exists": target.exists(),
            })
    return out


def freshness(store_stats: dict | None) -> dict:
    """Fresh start = empty store AND no user config. A folder that was wiped (or
    never existed) scans exactly like this."""
    scan = userdata.scan()
    records = (store_stats or {}).get("records", 0) or 0
    fresh = records == 0 and scan["config_files"] == 0
    return {"fresh_start": fresh, "records": records, "scan": scan}


def onboarding_hint() -> dict:
    """The prompt a driver surfaces to the user on a fresh start."""
    templates = find_templates()
    return {
        "message": ("No user context/knowledge/state found - this is a fresh "
                    "install (or the user-data folder was wiped). The framework "
                    "works; it just knows nothing about you yet."),
        "initialize": ("python scripts/run-agent.py orchestrator bootstrap "
                       "[--with-templates]"),
        "steps": [
            "Run bootstrap to seed the user-data folder (add --with-templates to "
            "copy each component's config template for you to fill in).",
            "Fill in the copied config templates (placeholders are marked; keep "
            "accounts disabled until real).",
            "Store credentials: python scripts/set-credential.py <tool> <secret> "
            "(scripts/list-tools.py shows what each tool is missing).",
            "Log in web sessions you need: run-tool web save-session --name <site> ...",
            "Start building context: curator remember / curator capture as facts, "
            "files and preferences come up - the store fills itself from use.",
        ],
        "templates": templates,
    }


def _readme_text() -> str:
    return """# context-state-knowledge/ - your data, not the framework's

Everything user-specific lives here: config, runtime state, knowledge, resources,
preferences, decisions, run history, exports. The folder is **never git-versioned**
and is **wipeable**: delete it and the framework still runs - it will detect the
fresh start and guide whoever uses it next through building new context. That is the
handover story: give the repo away, wipe this folder, done.

Generated by `orchestrator bootstrap` - do not keep notes here by hand; use the
curator (`curator remember` / `curator capture`) so knowledge stays structured.

## Layout

```
store.db            SQLite store (records + runs) - access ONLY via the
                    context-store tool or the curator agent
config/<component>/ per-component user config (seeded from each component's
                    <name>.template.json in the framework)
state/<component>/  per-component runtime state
sessions/           saved web login sessions (when migrated)
exports/            human-readable dumps (curator export)
```

## Rebuilding after a wipe

```
python scripts/run-agent.py orchestrator bootstrap --with-templates
```

Then fill in the copied templates, store credentials with
`python scripts/set-credential.py <tool> <secret>`, and start working - the
orchestrator/curator build the rest from use. Secrets NEVER live in this folder;
they stay in the OS credential store.
"""


def bootstrap(ctx, *, with_templates: bool = False) -> dict:
    """Seed/repair the user-data folder. Idempotent; never overwrites user files."""
    base = userdata.base()
    # Ensure the store schema exists - through the tool, honoring the one-code-path
    # rule. stats also tells us whether data already exists.
    stats = ctx.cs("stats")
    # Measure freshness BEFORE seeding: copying templates creates config files,
    # which would otherwise hide that this was a fresh install needing onboarding.
    fresh = freshness(stats)

    readme = base / "README.md"
    readme.write_text(_readme_text(), encoding="utf-8", newline="\n")

    # Materialize the standard areas so the layout is visible.
    for d in ("config", "state", "sessions", "exports"):
        (base / d).mkdir(parents=True, exist_ok=True)

    # Seed the schedule skeleton (commented, empty) so recurring work has a home.
    from agents.orchestrator import schedulelib
    seeded_schedule = schedulelib.ensure_skeleton()

    copied, skipped = [], []
    templates = find_templates()
    if with_templates:
        for t in templates:
            target = Path(t["target"])
            if target.exists():
                skipped.append(t["target"])
                continue
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copyfile(FRAMEWORK_ROOT / t["template"], target)
            copied.append(t["target"])

    return {
        "base": str(base),
        "store": stats,
        "readme": str(readme),
        "schedule_seeded": str(seeded_schedule) if seeded_schedule else None,
        "templates_found": len(templates),
        "templates_copied": copied,
        "templates_skipped_existing": skipped,
        "fresh_start": fresh["fresh_start"],
        "onboarding": onboarding_hint() if fresh["fresh_start"] else None,
        "note": ("templates were NOT copied; pass --with-templates to copy them"
                 if not with_templates else
                 "fill in the copied templates before enabling anything"),
    }
