"""UI copy for this distribution.

LBL is the generic interface vocabulary and is carried whole. S holds only
the page copy this distribution actually renders; the hero comes from the
engine's own fallback, so nothing here has to be authored by hand.
"""
from __future__ import annotations

LBL = {
    "en": {
        "ctl_collapse": "Collapse all",
        "ctl_expand": "Expand all",
        "ctl_search": "Search tools, agents, skills, actions...   e.g. whatsapp, invoice, search-people",
        "empty": "Nothing matches that search.",
        "exp_h2": "Explore everything",
        "exp_intro": "The full registry, straight from the manifests. Search by name or by what it does. Open a tool to see its actions, open an action to see its arguments. Green dot means its credentials are already in place. Names, commands, and the per-action technical notes stay in English, as in the terminal.",
        "exp_kicker": "Every capability, drillable",
        "l_actions": "Actions",
        "l_autotrigger": "auto-trigger",
        "l_creds": "Credentials it needs",
        "l_drives": "Drives these tools",
        "l_noargs": "no arguments",
        "l_opt": "opt",
        "l_primary": "Primary use",
        "l_req": "req",
        "l_triggers": "Triggers on",
        "l_when": "When it triggers &amp; what it does",
        "m_many": "matches",
        "m_one": "match",
        "nav_cases": "Use cases",
        "nav_explore": "Explore",
        "nav_line": "The line",
        "nav_loop": "The loop",
        "nav_pieces": "The pieces",
        "nav_platform": "The driver",
        "nav_prompts": "Prompts",
        "nav_schedules": "Schedules",
        "nav_store": "The store",
        "nav_together": "Working together",
        "nav_triggers": "Who triggers what",
        "tab_agents": "Agents",
        "tab_skills": "Skills",
        "tab_tools": "Tools",
        "tip_needs": "needs credentials",
        "tip_ready": "credentials present",
        "w_actions": "actions",
        "w_arg": "arg",
        "w_args": "args",
        "w_tools": "tools",
    },
    "ro": {
        "ctl_collapse": "Restrânge tot",
        "ctl_expand": "Extinde tot",
        "ctl_search": "Caută tool-uri, agenți, skill-uri, acțiuni...   ex. whatsapp, factură, search-people",
        "empty": "Nimic nu se potrivește cu căutarea.",
        "exp_h2": "Explorează tot",
        "exp_intro": "Registrul complet, direct din manifeste. Caută după nume sau după ce face. Deschide un tool ca să-i vezi acțiunile, deschide o acțiune ca să-i vezi argumentele. Punctul verde înseamnă că credentialele sunt deja la locul lor. Numele, comenzile și notele tehnice de la nivel de acțiune rămân în engleză, ca în terminal.",
        "exp_kicker": "Fiecare capabilitate, în detaliu",
        "l_actions": "Acțiuni",
        "l_autotrigger": "auto-declanșare",
        "l_creds": "Credentiale necesare",
        "l_drives": "Conduce aceste tool-uri",
        "l_noargs": "fără argumente",
        "l_opt": "opt",
        "l_primary": "Utilizare principală",
        "l_req": "oblig",
        "l_triggers": "Se declanșează la",
        "l_when": "Când se declanșează &amp; ce face",
        "m_many": "potriviri",
        "m_one": "potrivire",
        "nav_cases": "Exemple",
        "nav_explore": "Explorează",
        "nav_line": "Linia",
        "nav_loop": "Bucla",
        "nav_pieces": "Componentele",
        "nav_platform": "Driverul",
        "nav_prompts": "Prompturi",
        "nav_schedules": "Programări",
        "nav_store": "Memoria",
        "nav_together": "Cum lucrează împreună",
        "nav_triggers": "Cine declanșează ce",
        "tab_agents": "Agenți",
        "tab_skills": "Skill-uri",
        "tab_tools": "Tool-uri",
        "tip_needs": "lipsesc credentiale",
        "tip_ready": "credentiale prezente",
        "w_actions": "acțiuni",
        "w_arg": "arg",
        "w_args": "argumente",
        "w_tools": "tool-uri",
    },
}

S = {
    "en": {
        "footer": "Generated from the live manifests, $NTOOLS tools &middot; $NAGENTS agents &middot; $NSKILLS skills &middot; $NACTIONS actions. The registry is the source of truth, this map regenerates from it. Framework capability is shared and versioned, your data stays in <code>context-state-knowledge/</code>, secrets stay in the Windows Credential Store.",
    },
    "ro": {
        "footer": "Generat din manifestele vii, $NTOOLS tool-uri &middot; $NAGENTS agenți &middot; $NSKILLS skill-uri &middot; $NACTIONS acțiuni. Registrul e sursa de adevăr - harta asta se regenerează din el. Capabilitatea de framework e partajată și versionată, datele tale rămân în <code>context-state-knowledge/</code>, secretele rămân în Windows Credential Store.",
    },
}
