"""Generate the Capability Router block inside CLAUDE.md from the registry.

The router is a compact request->tool/agent map that auto-loads every session
(because CLAUDE.md is injected as project instructions). It lets a request be
matched to the right tool with zero discovery steps.

Source of truth is the registry (manifests). A tool can curate its own routing
via a `routing:` block in tool.yaml (triggers / primary_action / example); when
absent, this script falls back to the description and a heuristic primary action.

The block is a pure function of the manifests. Nothing machine-specific goes in
it - notably NOT which credentials the generating machine happens to hold, which
used to land here and made the committed CLAUDE.md differ per person (so the
sync test could only pass for whoever regenerated last). Live readiness belongs
to `list-tools.py` and the dashboard; here it is a stderr warning.

Usage:
  python scripts/build-router.py            # rewrite the block in CLAUDE.md
  python scripts/build-router.py --print    # print the block to stdout, write nothing
  python scripts/build-router.py --check    # exit 1 if CLAUDE.md is out of date (CI guard)
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Auto-switch to the project's .venv Python if launched with a different one.
_PROJECT_ROOT = Path(__file__).resolve().parents[1]
# .venv layout is per-OS: Scripts/python.exe on Windows, bin/python everywhere
# else. Hardcoding the Windows path made this a silent no-op on macOS/Linux,
# where the script then ran on whatever interpreter happened to invoke it.
_VENV_PY = (_PROJECT_ROOT / ".venv" / "Scripts" / "python.exe" if sys.platform == "win32"
            else _PROJECT_ROOT / ".venv" / "bin" / "python")
if _VENV_PY.exists() and Path(sys.executable).resolve() != _VENV_PY.resolve():
    import subprocess
    sys.exit(subprocess.run([str(_VENV_PY), __file__, *sys.argv[1:]]).returncode)

try:
    sys.stdout.reconfigure(encoding="utf-8")
except (AttributeError, ValueError):
    pass

sys.path.insert(0, str(_PROJECT_ROOT))

from registry import list_agents, list_skills, list_tools  # noqa: E402

START = "<!-- CAPABILITY-ROUTER:START — generated by scripts/build-router.py; rerun after adding/removing a tool. Do not hand-edit. -->"
END = "<!-- CAPABILITY-ROUTER:END -->"

# Actions that never make a good "first thing to reach for".
_AUTH_ACTIONS = {"auth-status", "auth-login", "auth-logout", "login", "auth", "web-login", "web-status"}

# Skills registered in this project (skills/<name>/) are generated from the
# registry below. This residual pointer covers harness-only skills that auto-
# trigger but are NOT bundled in this repo, so the router still routes to them.
# Keep terse. When a skill here gets imported into skills/, drop its line.
_HARNESS_SKILLS_POINTER = globals().get("_HARNESS_SKILLS_POINTER", [])


def _first_sentence(text: str, cap: int = 110) -> str:
    text = " ".join((text or "").split())
    for sep in (". ", " — ", "; "):
        if sep in text:
            text = text.split(sep, 1)[0]
            break
    return (text[: cap - 1] + "…") if len(text) > cap else text


def _primary_action(entry: dict) -> str:
    routing = entry.get("routing") or {}
    if routing.get("primary_action"):
        return routing["primary_action"]
    actions = [a["name"] for a in entry.get("actions", [])]
    non_auth = [a for a in actions if a not in _AUTH_ACTIONS]
    return (non_auth or actions or [""])[0]


def _trigger(entry: dict) -> str:
    routing = entry.get("routing") or {}
    if routing.get("triggers"):
        return "; ".join(routing["triggers"])
    return _first_sentence(entry.get("description", ""))


def _example(entry: dict, runner: str) -> str:
    routing = entry.get("routing") or {}
    if routing.get("example"):
        return routing["example"]
    action = _primary_action(entry)
    return f"{entry['name']} {action}".strip()


def _line(entry: dict, runner: str) -> str:
    return f"- **{entry['name']}** — {_trigger(entry)} → `{_example(entry, runner)}`"


def _skill_line(entry: dict) -> str:
    return f"- **{entry['name']}** — {_trigger(entry)} → `get-skill.py {entry['name']}`"


def build_block() -> tuple[str, list[str]]:
    """Return (markdown_block, warnings)."""
    warnings: list[str] = []
    tools = list_tools()
    agents = list_agents()

    # Listed by MANIFEST validity, not by local credential state. Filtering the
    # listing on `ready` was the same per-machine leak as the readiness line
    # below, only larger: a checkout that had not stored a tool's secret yet
    # silently dropped that tool from the router, so the agent stopped routing
    # to a capability that exists - and the committed file differed per person.
    # Whether YOU can run it is a live question (list-tools.py, the dashboard);
    # whether it EXISTS is a manifest question, and only that belongs here.
    listed = [t for t in tools if "error" not in t]
    not_ready = [t for t in tools if not t.get("ready") and "error" not in t]
    errored = [t for t in tools if "error" in t]

    for t in listed:
        if not t.get("routing"):
            warnings.append(f"tool '{t['name']}' has no curated routing: block (using description fallback)")

    lines = [START, ""]
    lines.append("### Tools — run with `python scripts/run-tool.py <tool> <action> [--args]`")
    lines.append("")
    for t in sorted(listed, key=lambda x: x["name"]):
        lines.append(_line(t, "run-tool.py"))
    lines.append("")

    # Deliberately NOT written into the block: which secrets are stored is a
    # property of one machine, and CLAUDE.md is version-controlled and shared
    # by two teams. Emitting it here made the generated file differ per person,
    # so the sync test could only pass on whoever committed last, and it put
    # user-specific data in a framework file the same document forbids it in.
    # The live answer belongs to `list-tools.py` and the dashboard; here it is
    # a stderr warning, so the information survives without being published.
    for t in sorted(not_ready, key=lambda x: x["name"]):
        miss = ",".join(t.get("missing_secrets", [])) or "credentials"
        warnings.append(f"tool '{t['name']}' needs credentials on this machine ({miss}) - not written to CLAUDE.md")

    if errored:
        bits = [t["name"] for t in errored]
        lines.append(f"❌ **Manifest errors** (fix before use): {', '.join(bits)}")
        lines.append("")

    if agents:
        lines.append("### Agents — run with `python scripts/run-agent.py <agent> <action> [--args]`")
        lines.append("")
        for a in sorted(agents, key=lambda x: x["name"]):
            if "error" in a:
                continue
            lines.append(_line(a, "run-agent.py"))
        lines.append("")

    skills = list_skills()
    skills_ready = [s for s in skills if "error" not in s]
    skills_errored = [s for s in skills if "error" in s]

    if skills or _HARNESS_SKILLS_POINTER:
        lines.append("### Skills")
        lines.append("")
        lines.append(
            "Claude **auto-triggers** these from their descriptions — do NOT run-tool them. "
            "Project agents discover them via the registry and load one's full content with "
            "`python scripts/get-skill.py <name> --content`."
        )
        lines.append("")

    if skills:
        lines.append("**Registered in this project** — run `python scripts/list-skills.py` (`skills/<name>/`):")
        lines.append("")
        for s in sorted(skills_ready, key=lambda x: x["name"]):
            lines.append(_skill_line(s))
            if not s.get("routing"):
                warnings.append(f"skill '{s['name']}' has no curated routing: block (using description fallback)")
        lines.append("")
        if skills_errored:
            bits = [s["name"] for s in skills_errored]
            lines.append(f"❌ **Skill manifest errors** (fix before use): {', '.join(bits)}")
            lines.append("")

    if _HARNESS_SKILLS_POINTER:
        lines.append("**Other harness skills** (auto-trigger; not bundled in this repo):")
        lines.append("")
        for s in _HARNESS_SKILLS_POINTER:
            lines.append(f"- {s}")
        lines.append("")
    lines.append(END)
    return "\n".join(lines), warnings


def splice(claude_md: str, block: str) -> str:
    if START in claude_md and END in claude_md:
        pre = claude_md.split(START, 1)[0].rstrip("\n")
        post = claude_md.split(END, 1)[1].lstrip("\n")
        return f"{pre}\n\n{block}\n\n{post}".rstrip() + "\n"
    # No markers yet: append a section at the end.
    return claude_md.rstrip() + "\n\n## Capability Router (auto-generated)\n\n" + block + "\n"


def main() -> int:
    # argparse, not `in sys.argv`: without it the no-argument path IS the
    # destructive one, so `build-router.py --help` rewrote CLAUDE.md instead of
    # explaining itself - a surprising way to dirty a clean working copy.
    parser = argparse.ArgumentParser(
        description="Regenerate the Capability Router block in CLAUDE.md from the "
                    "tool and agent manifests. With no flags it REWRITES CLAUDE.md.",
        epilog="The block is a pure function of the manifests: it carries no "
               "per-machine state, so every checkout generates the same bytes.",
    )
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--print", action="store_true",
                       help="Write the block to stdout and change nothing.")
    group.add_argument("--check", action="store_true",
                       help="Exit 1 if CLAUDE.md is out of date. Changes nothing.")
    args = parser.parse_args()

    block, warnings = build_block()
    claude_path = _PROJECT_ROOT / "CLAUDE.md"

    if args.print:
        print(block)
        for w in warnings:
            print(f"warning: {w}", file=sys.stderr)
        return 0

    current = claude_path.read_text(encoding="utf-8") if claude_path.exists() else ""
    updated = splice(current, block)

    if args.check:
        if current != updated:
            print("CLAUDE.md Capability Router is out of date — run scripts/build-router.py", file=sys.stderr)
            return 1
        print("CLAUDE.md Capability Router is up to date.")
        return 0

    claude_path.write_text(updated, encoding="utf-8")
    print(f"Wrote Capability Router to {claude_path} ({len(updated)} bytes).")
    for w in warnings:
        print(f"warning: {w}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
